# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarsSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'MBProgressHUD', '~> 1.0.0'
pod 'DynamicButton', '~> 4.0.0'
pod 'SwiftyJSON'
pod 'Alamofire','4.2.0'

  # Pods for CarsSearch

  target 'CarsSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarsSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
